### ISSUE TITLE
几个小问题

### ISSUE THREAD

**Issue by xiaojun678** [whr000001/DELL#2]
作者您好，您的工作对我有很大启发，但有几个小问题不太理解，希望能得到您的解答：
1. 论文里我理解的用户-新闻网络是指每个新闻有一个网络，节点是新闻+LLM生成的评论，对吧？
2. 如果我理解的1是对的，然后是针对每个任务会构建一个GNN，并预测新闻标签。这里我有一个问题是，例如对于情感分析任务，只通过LLM得到了对新闻关于情感方面的解释，最后将解释和新闻文本特征联立作为表征。那么对于GNN的其他节点，也就是生成的评论，这些节点的初始表征是什么呢？以及，对于评论表征的两个任务，单独运用其一可以表征评论节点，那这时新闻的表征又是如何构建？
本人目前还是小白，希望能得到您的解答，谢谢！

**Comment by whr000001** [comment]
I appreciate your interest in our work.

1. Yes, we generate a news-user interaction network for each news article.
2. We design content-related and comment-related proxy tasks. For content proxy content, we only enhance the content, where the content representation contains news content and the outputs of proxy tasks such as sentiment while the comment representation only contains comment content.

If you have more questions, feel free to ask.

**Comment by xiaojun678** [comment]
So the outputs of all six proxy tasks are used to enhance the news content representation rather than the comment representation, right?

**Comment by whr000001** [comment]
The four content-related tasks (including sentiment, framing, propaganda, and retrieval) are used to enhance the news content, while the two comment-related tasks (including stance, and response) are used to enhance the news comment.

**Comment by xiaojun678** [comment]
好的谢谢您的回复，所以是前四个任务用于增强新闻内容表征，后两个任务用于增强新闻评论表征。对于一个GNN，节点是1个新闻内容+若干个生成的新闻评论。然后我看了文章里提到每个任务都会单独构建一个GNN，那么问题是：假设对于任务1-情感，可以基于这个任务对第一个GNN的新闻内容进行增强表征，对新闻评论就只用其文本进行表征；或者对于任务6-回应，利用这个任务对第6个GNN进行新闻评论表征增强，然后新闻内容只用其文本进行表征，请问是这个意思吗？谢谢！

**Comment by whr000001** [comment]
Yes, you are right.
